### ISSUE TITLE
Add runner to blink project for esp32c3_devkitm board,but runner error

### ISSUE THREAD

**Issue by IOT4566** [mylonics/zephyr-ide#6]
![001](https://github.com/mylonics/zephyr-ide/assets/169084509/0f0aede4-38c0-42c3-bd3d-8a625407d9a7)
![002](https://github.com/mylonics/zephyr-ide/assets/169084509/4882ae4b-b721-4445-8f5c-a7a22c96103a)
![003](https://github.com/mylonics/zephyr-ide/assets/169084509/8c6ee59e-df7b-438e-b38e-93a59ffd4323)
![004](https://github.com/mylonics/zephyr-ide/assets/169084509/dc4e154a-f000-454d-b943-57e59f084371)
![005](https://github.com/mylonics/zephyr-ide/assets/169084509/754ff34d-d2af-48d4-87b6-3c4c116bba2c)

 1. pic1. Add runner to blink project for esp32c3_devkitm board, select default runner, but cann't run. 
pic2, I run cmd on powershell,  successful.  when select default runner , -r  (or --runner) is not given?

2. ESP32C3' runner is esp32 and openocd(see pic2, pic3, pic3), but runner 'esp32' is not in the runner list. 

3.  pic5 mean that for a specific board, the runner can be found by reading the board.cmake file under the board folder(see pic4 ), and other runners  that not belong to this board should not be in the runner list when user press add runner button 。

**Comment by rijesha** [comment]
Thanks for the issue. I will have a look at parsing the file.

**Comment by rijesha** [comment]
I added this into version 1.0.10. Should be available in a few minutes.

**Comment by rijesha** [comment]
builds that have already been made will have to be remade or the relBoardSubDir should be added manually into the settings.json file for preexisting builds.

**Comment by IOT4566** [comment]
> builds that have already been made will have to be remade or the relBoardSubDir should be added manually into the settings.json file for preexisting builds.

https://github.com/mylonics/zephyr-ide/assets/169084509/7624c808-d741-4ba8-b8e0-b8c6d54012d8

update to 1.0.10, but cann't add runner yet

**Comment by IOT4566** [comment]
> builds that have already been made will have to be remade or the relBoardSubDir should be added manually into the settings.json file for preexisting builds.

already rebuild,but cann't add runner

**Comment by rijesha** [comment]
It is working for me. Is there anything here?
Ctrl-Shift-p -> Show Logs -> Extension Host

**Comment by IOT4566** [comment]
> It is working for me. Is there anything here? Ctrl-Shift-p -> Show Logs -> Extension Host

2024-05-08 01:04:27.424 [error] Error: ENOENT: no such file or directory, open 'e:\zephyr\external\zephyr\boards\arm\esp32c3_devkitm\board.cmake'
	at Object.openSync (node:fs:605:3)
	at Object.func [as openSync] (node:electron/js2c/node_init:2:2214)
	at Object.readFileSync (node:fs:473:35)
	at t.readFileSync (node:electron/js2c/node_init:2:9771)
	at runnerSelector (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\project_utilities\runner_selector.js:51:31)
	at addRunnerToBuild (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\project_utilities\project.js:479:61)
	at a.value (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\panels\project_tree_view\ProjectTreeView.js:486:52)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at w.$onMessage (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:145:14048)
	at c.S (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5505)
	at c.Q (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5271)
	at c.M (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4361)
	at c.L (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3579)
	at a.value (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2227)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at a.value (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8023)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at MessagePortMain.<anonymous> (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6303)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
2024-05-08 01:04:34.061 [error] Error: ENOENT: no such file or directory, open 'e:\zephyr\external\zephyr\boards\arm\esp32c3_devkitm\board.cmake'
	at Object.openSync (node:fs:605:3)
	at Object.func [as openSync] (node:electron/js2c/node_init:2:2214)
	at Object.readFileSync (node:fs:473:35)
	at t.readFileSync (node:electron/js2c/node_init:2:9771)
	at runnerSelector (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\project_utilities\runner_selector.js:51:31)
	at addRunnerToBuild (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\project_utilities\project.js:479:61)
	at a.value (c:\Users\yangfan\.vscode\extensions\mylonics.zephyr-ide-1.0.10\out\panels\project_tree_view\ProjectTreeView.js:486:52)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at w.$onMessage (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:145:14048)
	at c.S (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5505)
	at c.Q (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5271)
	at c.M (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4361)
	at c.L (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3579)
	at a.value (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2227)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at a.value (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8023)
	at o.y (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
	at o.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
	at u.fire (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
	at MessagePortMain.<anonymous> (d:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6303)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)

**Comment by IOT4566** [comment]
> It is working for me. Is there anything here? Ctrl-Shift-p -> Show Logs -> Extension Host

![Uploading 001.png…]()

**Comment by IOT4566** [comment]
> It is working for me. Is there anything here? Ctrl-Shift-p -> Show Logs -> Extension Host

![001](https://github.com/mylonics/zephyr-ide/assets/169084509/8eeb71b3-cfdf-40c1-b92d-a4af128e66b6)

**Comment by IOT4566** [comment]
![003](https://github.com/mylonics/zephyr-ide/assets/169084509/33c30cff-247e-41b6-8ec7-aeaca3490f50)

Now can add runner for esp32c3_devkitm board, but when select default runner ,the error here still,  in this item, "-r default" in cmd should remove

**Comment by rijesha** [comment]
I have pushed an update to remove the "-r default" it is in v1.0.11

**Comment by IOT4566** [comment]
OK,this issuse is fixed perfect also

**Comment by IOT4566** [comment]
> I have pushed an update to remove the "-r default" it is in v1.0.11

![004](https://github.com/mylonics/zephyr-ide/assets/169084509/84ab6ff6-117e-4021-8312-94404e52cef3)

default runner lose args, should be added

**Comment by rijesha** [comment]
Update pushed.

**Comment by IOT4566** [comment]
> Update pushed.

OK, this issuse is fixed also
