### ISSUE TITLE
How to run Twister?

### ISSUE THREAD

**Issue by glenn-andrews** [mylonics/zephyr-ide#87]
On Windows 11. Building and running the app work, and show ZTest output in the terminal (which I then closed so it didn't interfere with Twister)

My test application is in `C:\EMBSYS330\embsys330_assignment_02\test_app` with `testcase.yaml` in that directory along with `CmakeLists.txt` and `prj.conf` and the source code is in `test_app\src`

```
C:\EMBSYS330\embsys330_assignment_02\test_app> west twister --device-testing --device-serial COM3 --device-serial-baud 115200 -p disco_l475_iot1  -T .
Traceback (most recent call last):
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\commands.py", line 559, in __call__
    mod = _commands_module_from_file(self.py_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\commands.py", line 714, in _commands_module_from_file
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\glenn\.zephyr_ide\external\zephyr\scripts\west_commands\twister_cmd.py", line 21, in <module>
    from twisterlib.twister_main import main
  File "C:\Users\glenn\.zephyr_ide\external\zephyr\scripts\pylib\twister\twisterlib\twister_main.py", line 20, in <module>
    from twisterlib.runner import TwisterRunner
  File "C:\Users\glenn\.zephyr_ide\external\zephyr\scripts\pylib\twister\twisterlib\runner.py", line 26, in <module>
    from domains import Domains
ModuleNotFoundError: No module named 'domains'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 561, in run_command
    self.run_extension(args.command, argv)
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 685, in run_extension
    self.cmd = self.extensions[name].factory()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\commands.py", line 561, in __call__
    raise ExtensionCommandError(
west.commands.ExtensionCommandError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\glenn\.zephyr_ide\.venv\Scripts\west.exe\__main__.py", line 7, in <module>
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 1176, in main
    app.run(argv or sys.argv[1:])
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 255, in run
    self.run_command(argv, early_args)
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 605, in run_command
    self.handle_extension_command_error(ece)
  File "C:\Users\glenn\.zephyr_ide\.venv\Lib\site-packages\west\app\main.py", line 431, in handle_extension_command_error
    self.cmd.err(msg, fatal=True)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'err'
```

**Comment by glenn-andrews** [comment]
I believe the 'package' is a build helper from here: https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/pylib/build_helpers/domains.py

> Does running the same test with the same parameters on the same version of zephyr, but without the zephyr ide work?

For this I assume you mean installing Zephyr in the `~/zephyrproject` directory and running from a separate virtual environment?

**Comment by glenn-andrews** [comment]
In the Zephyr IDE shell, typing `west twister` has the same crash but typing `west build` works (until it fails for lack of arguments)

**Comment by glenn-andrews** [comment]
My apologies. It appears to be the latest mainline Zephyr. Bisecting now.
